/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist;

import org.xtext.example.mydsl.ui.contentassist.AbstractVariCellProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class VariCellProposalProvider extends AbstractVariCellProposalProvider {

}
